### PR TITLE
Update missing locale entries

### PR DESCRIPTION
**Pull request by pfaffman**
What? Me? Plugins?

Do you maintain this or would it make more sense to fork it?

### CODE REVIEW

**Comment by joebuhlig** [comment]
It’s in the middle of a rebranding to ProCourse. So yes it is maintained.

**Comment by pfaffman** [comment]
So is my PR actually useful!?!

--
Jay Pfaffman <j <pfaffman@relaxpc.com>ay@pfaffman.com>
+1-865-226-9465

**Comment by joebuhlig** [comment]
That it is!

**Comment by pfaffman** [comment]
Sigh. No, it's not. I thought that I could make such a trivial change correctly, but that's not the case. I should have bothered to test it in my dev environment.

I'm still getting `[en.lockdown.lockdown_enabled]` and `[en.lockdown.lockdown_allowed_groups]:` in the category/settings modal.

**Pull request merged**
